# Generated by Django 5.2.4 on 2025-09-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='complemento',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
