# Generated by Django 5.2.4 on 2025-09-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_paciente_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='bairro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paciente',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cep',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cidade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cor',
            field=models.CharField(blank=True, choices=[('branca', 'Branca'), ('parda', 'Parda'), ('preta', 'Preta'), ('amarela', 'Amarela'), ('indigena', 'Indígena')], max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paciente',
            name='orgao_exp',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rg',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
