# Generated by Django 5.2.4 on 2025-09-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0004_paciente_bairro_paciente_celular_paciente_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('ensinoFundamental', 'Ensino Fundamental'), ('ensinoMedio', 'Ensino Médio'), ('superior', 'Superior')], max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)')], max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paciente',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='profissao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
