# Generated by Django 5.2.4 on 2025-10-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_paciente_escolaridade_paciente_estado_civil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='plano_convenio',
            field=models.CharField(blank=True, choices=[('unimed', 'Unimed'), ('ipasgo', 'IPASGO')], max_length=50),
        ),
    ]
