# Generated by Django 5.2.4 on 2025-10-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0006_paciente_plano_convenio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('ensinoFundamental', 'Ensino Fundamental'), ('ensinoMedio', 'Ensino Médio'), ('ensinoSuperior', 'Ensino Superior'), ('superiorIncompleto', 'Ensino Superior Incompleto')], max_length=50),
        ),
    ]
