# Generated by Django 5.2.4 on 2025-10-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0007_alter_paciente_escolaridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
