# Generated by Django 5.2.4 on 2025-10-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0008_alter_paciente_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
